/*
  # Insert sample kurti products

  1. Sample Data
    - Insert 20 sample kurti products with various categories, materials, and styles
    - Include realistic pricing, descriptions, and product details
    - Set some products as featured, new, or bestsellers
*/

INSERT INTO products (
  name, 
  description, 
  price, 
  original_price, 
  category, 
  size, 
  color, 
  material, 
  care_instructions,
  images, 
  stock_quantity, 
  is_featured, 
  is_new, 
  is_bestseller
) VALUES 
(
  'Elegant Cotton Kurti with Embroidery',
  'Beautiful cotton kurti featuring intricate hand embroidery work. Perfect for daily wear with comfort and style. The breathable fabric makes it ideal for all seasons.',
  1299,
  1799,
  'casual',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'blue',
  'cotton',
  'Machine wash cold, do not bleach, tumble dry low, iron on medium heat',
  ARRAY['https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=800'],
  25,
  true,
  true,
  false
),
(
  'Formal Silk Kurti with Gold Border',
  'Sophisticated silk kurti with elegant gold border detailing. Perfect for office wear and formal occasions. Features a contemporary cut with traditional elements.',
  2499,
  3299,
  'formal',
  ARRAY['S', 'M', 'L', 'XL'],
  'black',
  'silk',
  'Dry clean only, store in cool dry place, avoid direct sunlight',
  ARRAY['https://images.pexels.com/photos/7148971/pexels-photo-7148971.jpeg?auto=compress&cs=tinysrgb&w=800'],
  15,
  true,
  false,
  true
),
(
  'Party Wear Georgette Kurti',
  'Glamorous georgette kurti with sequin work and flowing silhouette. Designed for special occasions and evening parties. Features beautiful draping and comfortable fit.',
  3299,
  4499,
  'party',
  ARRAY['S', 'M', 'L', 'XL'],
  'red',
  'georgette',
  'Dry clean recommended, gentle hand wash if needed, do not wring',
  ARRAY['https://images.pexels.com/photos/6146969/pexels-photo-6146969.jpeg?auto=compress&cs=tinysrgb&w=800'],
  12,
  true,
  true,
  true
),
(
  'Festive Banarasi Silk Kurti',
  'Traditional Banarasi silk kurti with rich zari work. Perfect for festivals and celebrations. Features authentic handloom weaving and timeless design.',
  4999,
  6999,
  'festive',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'gold',
  'silk',
  'Dry clean only, handle with care, store with muslin cloth',
  ARRAY['https://images.pexels.com/photos/8939575/pexels-photo-8939575.jpeg?auto=compress&cs=tinysrgb&w=800'],
  8,
  true,
  false,
  true
),
(
  'Casual Linen Kurti',
  'Comfortable linen kurti perfect for everyday wear. Features a relaxed fit and breathable fabric. Ideal for hot weather and casual outings.',
  999,
  1399,
  'casual',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'white',
  'linen',
  'Machine wash cold, line dry, iron while damp for best results',
  ARRAY['https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=800'],
  30,
  false,
  true,
  false
),
(
  'Printed Cotton Kurti',
  'Vibrant printed cotton kurti with modern patterns. Comfortable and stylish for daily wear. Features colorfast printing and soft cotton fabric.',
  1199,
  1599,
  'casual',
  ARRAY['S', 'M', 'L', 'XL'],
  'pink',
  'cotton',
  'Machine wash cold, do not bleach, tumble dry low',
  ARRAY['https://images.pexels.com/photos/7148971/pexels-photo-7148971.jpeg?auto=compress&cs=tinysrgb&w=800'],
  20,
  false,
  false,
  true
),
(
  'Designer Chiffon Kurti',
  'Elegant chiffon kurti with designer cuts and flowing fabric. Perfect for formal events and office wear. Features sophisticated styling and comfortable fit.',
  2199,
  2899,
  'formal',
  ARRAY['S', 'M', 'L', 'XL'],
  'green',
  'chiffon',
  'Dry clean recommended, gentle hand wash in cold water',
  ARRAY['https://images.pexels.com/photos/6146969/pexels-photo-6146969.jpeg?auto=compress&cs=tinysrgb&w=800'],
  18,
  true,
  false,
  false
),
(
  'Embellished Party Kurti',
  'Stunning party kurti with heavy embellishments and mirror work. Perfect for weddings and special celebrations. Features intricate handwork and premium fabric.',
  3799,
  4999,
  'party',
  ARRAY['S', 'M', 'L', 'XL'],
  'purple',
  'georgette',
  'Dry clean only, handle embellishments with care',
  ARRAY['https://images.pexels.com/photos/8939575/pexels-photo-8939575.jpeg?auto=compress&cs=tinysrgb&w=800'],
  10,
  true,
  true,
  false
),
(
  'Traditional Block Print Kurti',
  'Authentic block print kurti with traditional motifs. Handcrafted by skilled artisans using natural dyes. Perfect for cultural events and festivals.',
  1799,
  2399,
  'festive',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'yellow',
  'cotton',
  'Hand wash recommended, use mild detergent, dry in shade',
  ARRAY['https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=800'],
  22,
  false,
  true,
  true
),
(
  'Modern Cut Cotton Kurti',
  'Contemporary cotton kurti with modern silhouette. Features asymmetrical hem and trendy design. Perfect for young professionals and college wear.',
  1399,
  1899,
  'casual',
  ARRAY['S', 'M', 'L', 'XL'],
  'blue',
  'cotton',
  'Machine wash cold, tumble dry low, iron on medium heat',
  ARRAY['https://images.pexels.com/photos/7148971/pexels-photo-7148971.jpeg?auto=compress&cs=tinysrgb&w=800'],
  25,
  false,
  false,
  false
),
(
  'Formal Rayon Kurti',
  'Professional rayon kurti with clean lines and sophisticated design. Perfect for office wear and business meetings. Features wrinkle-resistant fabric.',
  1699,
  2199,
  'formal',
  ARRAY['S', 'M', 'L', 'XL'],
  'black',
  'rayon',
  'Machine wash cold, hang dry, iron on low heat',
  ARRAY['https://images.pexels.com/photos/6146969/pexels-photo-6146969.jpeg?auto=compress&cs=tinysrgb&w=800'],
  20,
  true,
  false,
  false
),
(
  'Sequined Evening Kurti',
  'Glamorous evening kurti with all-over sequin work. Perfect for cocktail parties and evening events. Features comfortable lining and stunning sparkle.',
  4299,
  5799,
  'party',
  ARRAY['S', 'M', 'L', 'XL'],
  'gold',
  'georgette',
  'Dry clean only, store flat to prevent sequin damage',
  ARRAY['https://images.pexels.com/photos/8939575/pexels-photo-8939575.jpeg?auto=compress&cs=tinysrgb&w=800'],
  8,
  true,
  true,
  true
),
(
  'Handloom Cotton Kurti',
  'Authentic handloom cotton kurti supporting traditional weavers. Features unique texture and natural cotton comfort. Perfect for eco-conscious fashion lovers.',
  1599,
  2099,
  'casual',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'white',
  'cotton',
  'Hand wash preferred, use natural detergent, line dry',
  ARRAY['https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=800'],
  15,
  false,
  true,
  false
),
(
  'Festive Chanderi Kurti',
  'Luxurious Chanderi silk kurti with traditional weaving. Perfect for festivals and special occasions. Features lightweight fabric with rich texture.',
  3499,
  4699,
  'festive',
  ARRAY['S', 'M', 'L', 'XL'],
  'red',
  'silk',
  'Dry clean recommended, store in breathable fabric bag',
  ARRAY['https://images.pexels.com/photos/7148971/pexels-photo-7148971.jpeg?auto=compress&cs=tinysrgb&w=800'],
  12,
  true,
  false,
  true
),
(
  'Casual Khadi Kurti',
  'Comfortable khadi cotton kurti promoting sustainable fashion. Features natural texture and breathable fabric. Perfect for daily wear and casual outings.',
  1299,
  1699,
  'casual',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'green',
  'cotton',
  'Hand wash with mild soap, dry in shade, iron on medium heat',
  ARRAY['https://images.pexels.com/photos/6146969/pexels-photo-6146969.jpeg?auto=compress&cs=tinysrgb&w=800'],
  28,
  false,
  false,
  true
),
(
  'Office Wear Crepe Kurti',
  'Professional crepe kurti with structured silhouette. Perfect for corporate environments and formal meetings. Features wrinkle-free fabric and elegant design.',
  1899,
  2499,
  'formal',
  ARRAY['S', 'M', 'L', 'XL'],
  'navy',
  'crepe',
  'Machine wash cold, hang dry, minimal ironing required',
  ARRAY['https://images.pexels.com/photos/8939575/pexels-photo-8939575.jpeg?auto=compress&cs=tinysrgb&w=800'],
  18,
  false,
  false,
  false
),
(
  'Cocktail Velvet Kurti',
  'Luxurious velvet kurti perfect for cocktail parties and evening events. Features rich texture and elegant drape. Designed for special occasions.',
  3999,
  5299,
  'party',
  ARRAY['S', 'M', 'L', 'XL'],
  'maroon',
  'velvet',
  'Dry clean only, brush gently to maintain texture',
  ARRAY['https://images.pexels.com/photos/6311612/pexels-photo-6311612.jpeg?auto=compress&cs=tinysrgb&w=800'],
  10,
  true,
  true,
  false
),
(
  'Wedding Guest Kurti',
  'Elegant kurti perfect for wedding functions and celebrations. Features subtle embroidery and sophisticated design. Comfortable for long events.',
  2799,
  3699,
  'festive',
  ARRAY['S', 'M', 'L', 'XL'],
  'pink',
  'silk',
  'Dry clean recommended, store with care',
  ARRAY['https://images.pexels.com/photos/7148971/pexels-photo-7148971.jpeg?auto=compress&cs=tinysrgb&w=800'],
  14,
  true,
  false,
  false
),
(
  'Summer Cotton Kurti',
  'Lightweight cotton kurti perfect for summer weather. Features breathable fabric and comfortable fit. Ideal for hot climate and daily wear.',
  899,
  1299,
  'casual',
  ARRAY['S', 'M', 'L', 'XL', 'XXL'],
  'yellow',
  'cotton',
  'Machine wash cold, line dry in shade, iron on low heat',
  ARRAY['https://images.pexels.com/photos/6146969/pexels-photo-6146969.jpeg?auto=compress&cs=tinysrgb&w=800'],
  35,
  false,
  true,
  true
),
(
  'Designer Palazzo Set Kurti',
  'Complete kurti set with matching palazzo pants. Perfect for festive occasions and special events. Features coordinated design and comfortable fit.',
  2999,
  3999,
  'festive',
  ARRAY['S', 'M', 'L', 'XL'],
  'blue',
  'georgette',
  'Dry clean recommended for best results',
  ARRAY['https://images.pexels.com/photos/8939575/pexels-photo-8939575.jpeg?auto=compress&cs=tinysrgb&w=800'],
  16,
  true,
  true,
  true
);